# Generated by Django 6.0.1 on 2026-07-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
