# Generated by Django 6.0.1 on 2026-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_alter_content_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='approved', max_length=20),
        ),
    ]
